using System;
using System.Xml;

namespace Soriana.PPS.DecisionManager.Common.Cybersource.Common
{
    public class CybersourceFaultException : ApplicationException
    {
        #region Constructors
        public XmlDocument FaultDocument { get; }
        //
        // Summary:
        //     Gets the fault code.
        public XmlQualifiedName Code { get; }
        //
        // Summary:
        //     Gets the fault string.
        public override string Message { get; }
        //
        // Summary:
        //     Gets the request id generated by CyberSource. It will return null if the request
        //     id had not been generated when the server exception occurred.
        public string RequestID { get; }
        //
        // Summary:
        //     Returns the string representation of this exception suitable for logging.
        public string LogString { get; }
        #endregion
    }
}
